#GET https://drug-education-project-backend.herokuapp.com/

POST https://drug-education-project-backend.herokuapp.com/questions 
Content-Type: application/json

{  
   "userId":"-2421",
   "day1a":"yes",
   "day1b":"1",
   "day1c":"1",
   "day2a":"yes",
   "day2b":"",
   "day2c":"",
   "day3a":"",
   "day3b":"",
   "day3c":"",
   "day4a":"",
   "day4b":"",
   "day4c":"",
   "day5a":"",
   "day5b":"",
   "day5c":"",
   "day6a":"",
   "day6b":"",
   "day6c":"",
   "day7a":"",
   "day7b":"",
   "day7c":"",
   "day8a":"",
   "day8b":"",
   "day8c":"",
   "day9a":"",
   "day9b":"",
   "day9c":"",
   "day10a":"",
   "day10b":"",
   "day10c":"",
   "day11a":"",
   "day11b":"",
   "day11c":"",
   "day12a":"",
   "day12b":"",
   "day12c":"",
   "day13a":"",
   "day13b":"",
   "day13c":"",
   "day14a":"",
   "day14b":"",
   "day14c":"",
   "q1":"yes",
   "q2":"yes",
   "q3":null,
   "q4":null,
   "q5":null,
   "q6":null,
   "q7":null,
   "q8":null,
   "q9":null,
   "q10":null
}
