"""empty message

Revision ID: d09fbcfd73b8
Revises: 
Create Date: 2018-04-03 14:29:04.408059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09fbcfd73b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('day1', sa.Integer(), nullable=True),
    sa.Column('day2', sa.Integer(), nullable=True),
    sa.Column('day3', sa.Integer(), nullable=True),
    sa.Column('day4', sa.Integer(), nullable=True),
    sa.Column('day5', sa.Integer(), nullable=True),
    sa.Column('day6', sa.Integer(), nullable=True),
    sa.Column('day7', sa.Integer(), nullable=True),
    sa.Column('day8', sa.Integer(), nullable=True),
    sa.Column('day9', sa.Integer(), nullable=True),
    sa.Column('day10', sa.Integer(), nullable=True),
    sa.Column('day11', sa.Integer(), nullable=True),
    sa.Column('day12', sa.Integer(), nullable=True),
    sa.Column('day13', sa.Integer(), nullable=True),
    sa.Column('day14', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('students')
    # ### end Alembic commands ###
